export const MEXICAN_STATES = [
  { value: "ags", label: "Aguascalientes" },
  { value: "bc", label: "Baja California" },
  { value: "bcs", label: "Baja California Sur" },
  { value: "cam", label: "Campeche" },
  { value: "chp", label: "Chiapas" },
  { value: "chh", label: "Chihuahua" },
  { value: "cmx", label: "Ciudad de México" },
  { value: "coa", label: "Coahuila" },
  { value: "col", label: "Colima" },
  { value: "dur", label: "Durango" },
  { value: "gua", label: "Guanajuato" },
  { value: "gro", label: "Guerrero" },
  { value: "hid", label: "Hidalgo" },
  { value: "jal", label: "Jalisco" },
  { value: "mex", label: "Estado de México" },
  { value: "mic", label: "Michoacán" },
  { value: "mor", label: "Morelos" },
  { value: "nay", label: "Nayarit" },
  { value: "nl", label: "Nuevo León" },
  { value: "oax", label: "Oaxaca" },
  { value: "pue", label: "Puebla" },
  { value: "que", label: "Querétaro" },
  { value: "roo", label: "Quintana Roo" },
  { value: "slp", label: "San Luis Potosí" },
  { value: "sin", label: "Sinaloa" },
  { value: "son", label: "Sonora" },
  { value: "tab", label: "Tabasco" },
  { value: "tam", label: "Tamaulipas" },
  { value: "tla", label: "Tlaxcala" },
  { value: "ver", label: "Veracruz" },
  { value: "yuc", label: "Yucatán" },
  { value: "zac", label: "Zacatecas" },
] as const;
